name: Build Linux

on:
  # Allow manual runs
  workflow_dispatch:
  # Run on any push to `master`
  push:
    branches:
    - master
  # Definitely run on any PR
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out repository

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        outputs: type=local,dest=bin
        platforms: linux/amd64,linux/arm64

    - name: Publish amd64 executables
      uses: actions/upload-artifact@v3
      with:
        name: amcduke32_linux_amd64.zip
        path: bin/linux_amd64/*

    - name: Publish arm64 executables
      uses: actions/upload-artifact@v3
      with:
        name: amcduke32_linux_arm64.zip
        path: bin/linux_arm64/*

    # TODO: automatically create a GitHub release when a tag is created
    # TODO: see about building Windows executables too
