name: Build amcduke32

on:
  workflow_dispatch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        outputs:
        - type=local,dest=bin
        platforms: linux/amd64,linux/arm64
        
    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: amcduke32
        path: bin
